#!/bin/sh

# script/release: build binaries in all supported platforms and upload them with the gh client

set -e

cd "$(dirname "$0")/.."

# this is also set in script/build and is a copy paste
GIT_SHA=`git rev-parse --short HEAD`
VERSION=$1
LDFLAGS="-X github.com/rsvihladremio/json2obj/cmd.GitSha=$GIT_SHA -X github.com/rsvihladremio/json2obj/cmd.Version=$VERSION"

echo "Cleaning bin folder…"
date "+%H:%M:%S"
./script/clean


echo "Building linux-amd64…"
date "+%H:%M:%S"
GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS" -o ./bin/json2obj
zip ./bin/json2obj-$VERSION-linux-amd64.zip ./bin/json2obj
echo "Building linux-arm64…"
date "+%H:%M:%S"
GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS" -o ./bin/json2obj
zip ./bin/json2obj-$VERSION-linux-arm64.zip ./bin/json2obj
echo "Building darwin-os-x-amd64…"
date "+%H:%M:%S"
GOOS=darwin GOARCH=amd64 go build -ldflags "$LDFLAGS" -o ./bin/json2obj
zip ./bin/json2obj-$VERSION-darwin-amd64.zip ./bin/json2obj
echo "Building darwin-os-x-arm64…"
date "+%H:%M:%S"
GOOS=darwin GOARCH=arm64 go build -ldflags "$LDFLAGS" -o ./bin/json2obj
zip ./bin/json2obj-$VERSION-darwin-arm64.zip ./bin/json2obj
echo "Building windows-amd64…"
date "+%H:%M:%S"
GOOS=windows GOARCH=amd64 go build -ldflags "$LDFLAGS" -o ./bin/json2obj.exe
zip ./bin/json2obj-$VERSION-windows-amd64.zip ./bin/json2obj.exe
echo "Building windows-arm64…"
date "+%H:%M:%S"
GOOS=windows GOARCH=arm64 go build -ldflags "$LDFLAGS" -o ./bin/json2obj.exe
zip ./bin/json2obj-$VERSION-windows-arm64.zip ./bin/json2obj.exe

gh release create $VERSION --title $VERSION -d -F changelog.md ./bin/json2obj-$VERSION-windows-arm64.zip ./bin/json2obj-$VERSION-windows-amd64.zip ./bin/json2obj-$VERSION-darwin-arm64.zip ./bin/json2obj-$VERSION-darwin-amd64.zip ./bin/json2obj-$VERSION-linux-arm64.zip ./bin/json2obj-$VERSION-linux-amd64.zip 
 